version: '3.7'
services:
  jammerdb:
    container_name: jammerdb
    image: mysql:8.0
    volumes:
      - ../mysqljammer:/var/lib/mysql
    ports:
      - "33069:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=jammer
  api:
    build: "."
    container_name: jammerapi
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always